# Generated by Django 5.2.12 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='require_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchparty',
            name='require_mic',
            field=models.BooleanField(default=False),
        ),
    ]
