# Generated by Django 5.2.12 on 2026-03-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='anime.anime'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('anime', 'number')},
        ),
    ]
