# Generated by Django 5.2.12 on 2026-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_rename_ganre_to_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='kind',
            field=models.CharField(choices=[('anime', 'Anime'), ('drama', 'Drama'), ('film', 'Kino')], db_index=True, default='anime', max_length=8),
        ),
    ]
