# Generated by Django 5.2.12 on 2026-09-20 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_profile_lists_and_kind'),
        ('users', '0002_alter_customuser_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autoplay_next',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_audio',
            field=models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Ko‘ryapman'), ('completed', 'Ko‘rib bo‘ldim'), ('planned', 'Reja'), ('dropped', 'Tashladim'), ('favorite', 'Sevimli')], max_length=16)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'anime'), name='uniq_user_anime_list')],
            },
        ),
    ]
