# Generated by Django 5.2.12 on 2026-09-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_photo_telegram_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='kind',
            field=models.CharField(choices=[('new_season', 'Yangi sezon'), ('new_episode', 'Yangi qism'), ('news', 'Yangilik')], max_length=16),
        ),
    ]
