# Generated by Django 5.2.12 on 2026-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_trigram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='release_year',
        ),
        migrations.AddField(
            model_name='anime',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ganre',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ganre',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ganre',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='season',
            name='release_date',
            field=models.IntegerField(default=2000),
        ),
    ]
