# Generated by Django 5.2.12 on 2026-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_trigram'),
        ('episode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='episodes/thumbs/'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('episode', 'language')},
        ),
    ]
