# Generated by Django 5.2.12 on 2026-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
