# Generated by Django 5.2.12 on 2026-03-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_episode_title_ru_episode_title_uz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
