# Generated by Django 5.2.12 on 2026-09-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0004_alter_video_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='episodes/videos/'),
        ),
    ]
