#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Animee · AWS S3 media"

stage "AWS hisobi"
say "S3 — Amazon Web Services ichidagi fayl ombori. Videolar server diskida emas, shu yerda yotadi."
step "Agar hisobingiz bo‘lmasa: Create an AWS Account."
step "Bo‘lsa: tizimga kiring."
open_url "https://console.aws.amazon.com/"
pause "Konsol ochildimi? Enter."

stage "S3 bucket"
say "Bucket — videolar yotadigan quti. Nom dunyo bo‘yicha unique bo‘lishi kerak."
open_url "https://s3.console.aws.amazon.com/s3/bucket/create?region=eu-central-1"
step "Bucket name: masalan animee-media-XXXX (XXXX o‘zingiz qo‘shing)."
step "AWS Region: Europe (Frankfurt) eu-central-1 — O‘zbekistonga yaqin."
step "Object Ownership: ACLs disabled (default) — o‘zgartirmang."
step "Block Public Access: hammasini yoqiq qoldiring (ON). Videolar imzoli havola bilan ochiladi."
step "Versioning: Disable. Encryption: default. Create bucket."
ask AWS_STORAGE_BUCKET_NAME "Bucket nomini yozing:"
ask AWS_S3_REGION_NAME "Region (Enter = eu-central-1):"
[[ -z "${AWS_S3_REGION_NAME}" ]] && AWS_S3_REGION_NAME="eu-central-1"
write_env AWS_STORAGE_BUCKET_NAME "$AWS_STORAGE_BUCKET_NAME"
write_env AWS_S3_REGION_NAME "$AWS_S3_REGION_NAME"

stage "Bucket CORS"
say "Brauzer HLS segmentlarni S3 dan o‘qishi uchun CORS kerak."
open_url "https://s3.console.aws.amazon.com/s3/buckets/${AWS_STORAGE_BUCKET_NAME}?region=${AWS_S3_REGION_NAME}&tab=permissions"
step "Permissions → Cross-origin resource sharing (CORS) → Edit."
step "Quyidagini to‘liq paste qiling, Save:"
say "["
say "  {"
say "    \"AllowedHeaders\": [\"*\"],"
say "    \"AllowedMethods\": [\"GET\", \"HEAD\"],"
say "    \"AllowedOrigins\": [\"*\"],"
say "    \"ExposeHeaders\": [\"Accept-Ranges\", \"Content-Length\", \"Content-Range\", \"ETag\"],"
say "    \"MaxAgeSeconds\": 3000"
say "  }"
say "]"
pause "CORS saqlandimi? Enter."

stage "IAM foydalanuvchi"
say "Django ga butun AWS hisobini bermang. Faqat shu bucket uchun alohida user."
open_url "https://console.aws.amazon.com/iam/home#/users"
step "Create user. Nom: animee-s3. Next."
step "Attach policies directly → Create policy → JSON. Quyidagini paste qiling (BUCKET o‘rniga o‘z nomingiz):"
say "{"
say "  \"Version\": \"2012-10-17\","
say "  \"Statement\": ["
say "    {"
say "      \"Effect\": \"Allow\","
say "      \"Action\": [\"s3:PutObject\", \"s3:GetObject\", \"s3:DeleteObject\", \"s3:ListBucket\"],"
say "      \"Resource\": ["
say "        \"arn:aws:s3:::${AWS_STORAGE_BUCKET_NAME}\","
say "        \"arn:aws:s3:::${AWS_STORAGE_BUCKET_NAME}/*\""
say "      ]"
say "    }"
say "  ]"
say "}"
step "Policy name: animee-s3-media. Create policy."
step "User yaratishga qayting, shu policyni belgilang, Create user."
pause "User tayyor bo‘lsa Enter."

stage "Access key"
say "Access key + Secret — .env ga yoziladi. Secret faqat bir marta ko‘rinadi."
open_url "https://console.aws.amazon.com/iam/home#/users"
step "animee-s3 user → Security credentials → Create access key."
step "Use case: Application running outside AWS. Next → Create access key."
step "Access key ID ni nusxalang. Secret access key ni Reveal qilib nusxalang."
warn "Secret ni chatga, GitHubga, screenshotga qo‘ymang."
ask AWS_ACCESS_KEY_ID "Access key ID:"
ask_secret AWS_SECRET_ACCESS_KEY "Secret access key:"
write_env AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
write_env AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"

stage "Tekshiruv"
say "Kalitlar .env da. Serverni qayta ishga tushiring, dashboarddan bitta qisqa video yuklang."
note "ffmpeg hali ham serverda ishlaydi (vaqtinchalik tmp). Tayyor HLS S3 ga ketadi, diskda qolmaydi."
note "Kalitlarni chatga yubormang — .env yetarli."
pause "Enter — yakun."

finish
