# Generated by Django 5.2.12 on 2026-03-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0002_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('age', models.CharField(max_length=3)),
                ('photo', models.ImageField(upload_to='person_photos/')),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='anime.anime')),
            ],
        ),
    ]
